Upgrade to Rails 8
sul-dlss/stacks pull request #1320
Opened 2024-12-03 18:00 UTC by jcoyne

2025-01-24 21:38 UTC, dnoneill requested changes
remove icon files

2025-01-24 21:48 UTC, jcoyne commented
This is only updating existing icon files, which already exist.  The removal is happening in https://github.com/sul-dlss/stacks/pull/1359 as they are no longer used when we switch to the icons in the component library.

2025-01-28 18:28 UTC, jcoyne commented
@dnoneill Icon files have been removed

2025-01-28 21:23 UTC, dnoneill approved these changes

2025-01-28 21:23 UTC, merged